-- PipeFlowCo database source of truth
--
-- Do not apply a second, standalone schema here. Database structure and RLS
-- live in the ordered Supabase migrations:
--   supabase/migrations/20250101000000_initial_schema.sql
--   supabase/migrations/20260924000000_forms_auth_fixes.sql
--   supabase/migrations/20260925000000_website_cms.sql
--   supabase/migrations/20260925110000_rls_tightening.sql
--   supabase/migrations/20260925120000_persist_site_and_seo_settings.sql
--
-- Canonical content tables:
-- homepage_content(id, content, updated_at)
-- service_categories, services, service_areas, blogs, testimonials, faqs, media
-- Leads, bookings and pro_applications remain private and are written by their
-- server API routes. Public CMS reads are restricted by the migration policies.
