/**
 * Writes supabase/migrations/20261009000100_seed_cms_pages.sql from
 * supabase/seed/pages.ts.   Run: npm run seed:sql
 *
 * The migration is idempotent: a page is only created when no live page
 * already uses its path, so re-running it never overwrites the client's edits.
 */
import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { seedPages } from '../supabase/seed/pages.ts'

export const OUTPUT = 'supabase/migrations/20261009000100_seed_cms_pages.sql'

/** Stable ids so regenerating the file produces the same SQL. */
function stableUuid(seed: string): string {
  const h = createHash('sha1').update(`pipeflow-seed:${seed}`).digest('hex')
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`
}

const q = (value: string) => {
  // $tag$$tag$ is ambiguous to Postgres, so the empty homepage path is written as ''.
  if (value === '') return "''"
  if (value.includes('$cms_seed$')) throw new Error('seed text must not contain $cms_seed$')
  return `$cms_seed$${value}$cms_seed$`
}
const nullable = (value?: string) => (value ? q(value) : 'NULL')

export function buildSeedSql(): string {
  const blocks = seedPages.map((page) => {
    const sections = page.sections.map((s, i) => ({ id: stableUuid(`${page.path}#${i}`), ...s }))
    const publish = page.isTemplate || page.draft ? '' : '    PERFORM cms_publish(v_id, 1, NULL);\n'
    return `DO $$
DECLARE v_id UUID;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cms_pages WHERE path = ${q(page.path)} AND deleted_at IS NULL) THEN
    v_id := cms_create_page(
      ${q(page.title)},
      ${q(page.path)},
      ${nullable(page.description)},
      ${q(JSON.stringify(sections))}::jsonb,
      ${nullable(page.seoTitle)},
      ${nullable(page.seoDescription)},
      NULL,
      NULL,
      ${page.noindex ? 'true' : 'false'},
      ${page.isTemplate ? 'true' : 'false'},
      NULL
    );
${publish}  END IF;
END $$;
`
  })
  return `-- GENERATED by scripts/generate-seed-sql.ts from supabase/seed/pages.ts. Do not edit by hand.
-- Launch pages built from the client's documents. Safe to re-run: existing paths are left alone.
-- Pages whose copy is still a starter are published with noindex set, so search engines skip
-- them until the client writes the real content and clears that box in the editor.

${blocks.join('\n')}`
}

// Only write the file when run directly, not when a test imports buildSeedSql.
if (process.argv[1]?.endsWith('generate-seed-sql.ts')) {
  writeFileSync(OUTPUT, buildSeedSql())
  console.log(`Wrote ${OUTPUT} (${seedPages.length} pages)`)
}
