import type { SiteConfig } from '@/types'

/**
 * Default site configuration.
 * All values marked [PLACEHOLDER] must be replaced with real business data
 * through the admin panel once Supabase is configured.
 */
export const siteConfig: SiteConfig = {
  company: {
    name: 'PipeFlow Co.',
    tagline: 'Flowing Comfort. Built to Last.',
    phone: '(720) 555-0100', // [PLACEHOLDER — replace with real number]
    email: 'hello@pipeflowco.com', // [PLACEHOLDER — replace with real email]
    address: '123 Main Street', // [PLACEHOLDER — replace with real address]
    city: 'Denver',
    state: 'CO',
    zip: '80202', // [PLACEHOLDER]
    license: 'LICENSE# [PLACEHOLDER]',
  },

  nav: [
    { label: 'Home', href: '/' },
    { label: 'Services', href: '/services' },
    { label: 'Service Areas', href: '/service-areas' },
    { label: 'About', href: '/about' },
    { label: 'Blog', href: '/blog' },
    { label: 'Join as a Pro', href: '/join-us' },
    { label: 'Contact', href: '/contact' },
  ],

  ctas: {
    bookService: { label: 'Book a Service', href: '/book-service' },
    getQuote: { label: 'Get a Quote', href: '/get-a-quote' },
    callNow: { label: 'Call Now', phone: '(720) 555-0100' }, // [PLACEHOLDER]
    joinPro: { label: 'Join PipeFlow', href: '/join-us' },
  },

  announcement: {
    enabled: true,
    messages: [
      '⚡ Same-Day Service Available — Call Now',
      '🚨 24/7 Emergency Plumbing & HVAC Response',
      '📍 Serving Denver & Surrounding Colorado Communities',
    ],
  },

  defaultServiceAreas: [
    {
      id: '1',
      name: 'Denver',
      slug: 'denver',
      state: 'CO',
      zipCodes: ['80202', '80203', '80204', '80205', '80206', '80207', '80209', '80210', '80211', '80212', '80218', '80220'],
      active: true,
      primary: true,
    },
    {
      id: '2',
      name: 'Aurora',
      slug: 'aurora',
      state: 'CO',
      zipCodes: ['80010', '80011', '80012', '80013', '80014', '80015', '80016', '80017'],
      active: true,
      primary: false,
    },
    {
      id: '3',
      name: 'Lakewood',
      slug: 'lakewood',
      state: 'CO',
      zipCodes: ['80214', '80215', '80226', '80227', '80228', '80232'],
      active: true,
      primary: false,
    },
    {
      id: '4',
      name: 'Englewood',
      slug: 'englewood',
      state: 'CO',
      zipCodes: ['80110', '80111', '80112', '80113'],
      active: true,
      primary: false,
    },
    {
      id: '5',
      name: 'Littleton',
      slug: 'littleton',
      state: 'CO',
      zipCodes: ['80120', '80121', '80122', '80123', '80127', '80128'],
      active: true,
      primary: false,
    },
    {
      id: '6',
      name: 'Arvada',
      slug: 'arvada',
      state: 'CO',
      zipCodes: ['80001', '80002', '80003', '80004', '80005', '80007'],
      active: true,
      primary: false,
    },
    {
      id: '7',
      name: 'Westminster',
      slug: 'westminster',
      state: 'CO',
      zipCodes: ['80020', '80021', '80030', '80031'],
      active: true,
      primary: false,
    },
    {
      id: '8',
      name: 'Thornton',
      slug: 'thornton',
      state: 'CO',
      zipCodes: ['80229', '80233', '80241', '80260'],
      active: true,
      primary: false,
    },
    {
      id: '9',
      name: 'Centennial',
      slug: 'centennial',
      state: 'CO',
      zipCodes: ['80015', '80112', '80121', '80122'],
      active: true,
      primary: false,
    },
    {
      id: '10',
      name: 'Parker',
      slug: 'parker',
      state: 'CO',
      zipCodes: ['80134', '80138'],
      active: true,
      primary: false,
    },
    {
      id: '11',
      name: 'Brighton',
      slug: 'brighton',
      state: 'CO',
      zipCodes: ['80601', '80602', '80603'],
      active: true,
      primary: false,
    },
    {
      id: '12',
      name: 'Castle Rock',
      slug: 'castle-rock',
      state: 'CO',
      zipCodes: ['80104', '80108', '80109'],
      active: true,
      primary: false,
    },
  ],

  defaultServices: [
    // PLUMBING (6 services as specified)
    {
      id: 'plumb-1',
      title: 'Leak Repair',
      slug: 'leak-repair',
      category: 'plumbing',
      shortDescription: 'Pinpoint acoustic & thermal leak detection for hidden copper, PEX, and slab pipe leaks.',
      description: 'Comprehensive leak detection and non-invasive pipe repairs to protect your foundation and drywall.',
      iconName: 'search',
      featured: true,
      emergency: true,
    },
    {
      id: 'plumb-2',
      title: 'Drain Cleaning',
      slug: 'drain-cleaning',
      category: 'plumbing',
      shortDescription: 'Heavy-duty snaking & hydro-jetting to clear stubborn clogs in sinks, tubs, and main lines.',
      description: 'High-pressure hydro-jetting and motorized augers that clear tough roots, grease, and debris.',
      iconName: 'droplets',
      featured: true,
      emergency: true,
    },
    {
      id: 'plumb-3',
      title: 'Water Heater',
      slug: 'water-heater',
      category: 'plumbing',
      shortDescription: 'Fast repairs, tank flush, and premium tankless or traditional water heater installations.',
      description: 'Expert diagnostics for gas, electric, and tankless units. Same-day emergency replacements available.',
      iconName: 'flame',
      featured: true,
      emergency: false,
    },
    {
      id: 'plumb-4',
      title: 'Pipe Repair & Repiping',
      slug: 'pipe-repair',
      category: 'plumbing',
      shortDescription: 'Frozen pipe thawing, burst pipe repair, and whole-home PEX re-piping solutions.',
      description: 'Built for Colorado temperature swings. Rapid winter freeze response and durable long-term upgrades.',
      iconName: 'wrench',
      featured: true,
      emergency: true,
    },
    {
      id: 'plumb-5',
      title: 'Faucet & Fixture Repair',
      slug: 'faucet-fixture-repair',
      category: 'plumbing',
      shortDescription: 'Precision repair and replacement for leaky faucets, running toilets, and modern fixtures.',
      description: 'Professional installation and repair of kitchen faucets, bathroom vanities, showers, and pressure regulators.',
      iconName: 'zap',
      featured: false,
      emergency: false,
    },
    {
      id: 'plumb-6',
      title: 'Sewer Services',
      slug: 'sewer-services',
      category: 'plumbing',
      shortDescription: 'HD video camera sewer inspections, trenchless pipe lining, and main sewer line clearing.',
      description: 'Accurate camera diagnostics and trenchless rehabilitation to fix broken or root-intruded sewer laterals.',
      iconName: 'alert-triangle',
      featured: false,
      emergency: true,
    },

    // HVAC (6 services as specified)
    {
      id: 'hvac-1',
      title: 'AC Repair',
      slug: 'ac-repair',
      category: 'hvac',
      shortDescription: 'Fast cooling diagnostics for refrigerant leaks, blown capacitors, frozen coils, and poor airflow.',
      description: 'Prompt troubleshooting and repairs to restore icy cool air quickly during hot Front Range summers.',
      iconName: 'wind',
      featured: true,
      emergency: true,
    },
    {
      id: 'hvac-2',
      title: 'AC Installation',
      slug: 'ac-installation',
      category: 'hvac',
      shortDescription: 'High-efficiency central air and ductless mini-split systems tailored to your home layout.',
      description: 'Properly sized energy-saving systems installed to maximize comfort and reduce monthly electric bills.',
      iconName: 'wind',
      featured: true,
      emergency: false,
    },
    {
      id: 'hvac-3',
      title: 'Heating / Furnace',
      slug: 'heating-furnace',
      category: 'hvac',
      shortDescription: 'Emergency furnace repairs, heat exchanger inspections, and reliable new heating installations.',
      description: 'Ensuring your home stays warm through freezing Colorado winter nights with licensed furnace experts.',
      iconName: 'thermometer',
      featured: true,
      emergency: true,
    },
    {
      id: 'hvac-4',
      title: 'HVAC Maintenance',
      slug: 'hvac-maintenance',
      category: 'hvac',
      shortDescription: 'Comprehensive multi-point seasonal tune-ups to extend equipment life and avoid costly breakdowns.',
      description: 'Seasonal safety checks, airflow calibration, electrical testing, and filter changes.',
      iconName: 'shield-check',
      featured: false,
      emergency: false,
    },
    {
      id: 'hvac-5',
      title: 'Heat Pumps',
      slug: 'heat-pumps',
      category: 'hvac',
      shortDescription: 'Cold-climate hybrid and all-electric heat pump systems engineered for Rocky Mountain weather.',
      description: 'Dual-fuel and cold-climate heat pump solutions that deliver year-round heating and cooling efficiently.',
      iconName: 'zap',
      featured: false,
      emergency: false,
    },
    {
      id: 'hvac-6',
      title: 'Indoor Air Quality',
      slug: 'indoor-air-quality',
      category: 'hvac',
      shortDescription: 'Whole-home humidifiers, HEPA filtration, and air purifiers to combat dry Colorado air and dust.',
      description: 'Steam humidifiers, MERV-rated filtration, and UV sanitizers to protect family respiratory health.',
      iconName: 'droplets',
      featured: false,
      emergency: false,
    },
  ],

  defaultTrustPrinciples: [
    {
      id: 'tp-1',
      title: 'Clear Communication',
      description: 'We explain the issue in plain English, outline your options, and provide upfront pricing before touching a tool.',
      iconName: 'message-square',
    },
    {
      id: 'tp-2',
      title: 'Qualified Professionals',
      description: 'All work is performed by vetted, licensed plumbers and HVAC technicians equipped with modern diagnostic tools.',
      iconName: 'award',
    },
    {
      id: 'tp-3',
      title: 'Reliable Scheduling',
      description: 'We respect your day with confirmed appointment windows, on-time arrivals, and proactive dispatch updates.',
      iconName: 'clock',
    },
    {
      id: 'tp-4',
      title: 'Quality Workmanship',
      description: 'We install premium-grade parts, follow strict Colorado code compliance, and back our labor with workmanship warranties.',
      iconName: 'shield-check',
    },
    {
      id: 'tp-5',
      title: 'Respect for Your Home',
      description: 'Clean drop cloths, protective shoe covers on every visit, and leaving your living space spotless when the job is done.',
      iconName: 'home',
    },
  ],

  defaultHowItWorks: [
    {
      step: 1,
      title: 'Tell Us What You Need',
      description: 'Submit an online request or call our dispatch team directly. Select plumbing or HVAC and describe your issue.',
      iconName: 'clipboard-list',
    },
    {
      step: 2,
      title: 'Choose a Service Time',
      description: 'Pick an appointment window that suits your calendar, or request immediate same-day emergency dispatch.',
      iconName: 'calendar',
    },
    {
      step: 3,
      title: 'A Qualified Pro Helps',
      description: 'A licensed PipeFlow technician arrives on time, inspects the problem, and gives you transparent upfront solutions.',
      iconName: 'wrench',
    },
    {
      step: 4,
      title: 'Get Back to Comfort',
      description: 'Your plumbing or heating/cooling system is fixed right the first time, backed by our quality standard.',
      iconName: 'smile',
    },
  ],

  defaultSpecialOffer: {
    id: 'offer-spring-2025',
    badge: 'Seasonal Service Special',
    title: 'Whole-Home Plumbing & HVAC Health Inspection',
    description:
      'Comprehensive safety and performance inspection covering water pressure, furnace combustion, cooling efficiency, and drain health.',
    discountCode: 'COLORADOCARE',
    disclaimer: '[PLACEHOLDER] Limited time seasonal offer. Valid for residential homeowners in PipeFlow Denver service territories.',
    ctaText: 'Claim This Offer',
    ctaHref: '/book?offer=inspection',
    active: true,
  },

  defaultTestimonials: [
    {
      id: '1',
      reviewerName: '[PLACEHOLDER — Real Customer Name]',
      reviewerCity: 'Denver, CO',
      rating: 5,
      reviewText:
        '[PLACEHOLDER — Add real customer reviews through the admin panel. Do not publish placeholder testimonials publicly.]',
      serviceName: 'Drain Cleaning & Hydro-Jetting',
      date: '2024-11-15',
      verified: true,
      source: 'google',
    },
    {
      id: '2',
      reviewerName: '[PLACEHOLDER — Real Customer Name]',
      reviewerCity: 'Aurora, CO',
      rating: 5,
      reviewText:
        '[PLACEHOLDER — Add real customer reviews through the admin panel. Do not publish placeholder testimonials publicly.]',
      serviceName: 'Furnace Emergency Heating Repair',
      date: '2024-12-04',
      verified: true,
      source: 'google',
    },
    {
      id: '3',
      reviewerName: '[PLACEHOLDER — Real Customer Name]',
      reviewerCity: 'Lakewood, CO',
      rating: 5,
      reviewText:
        '[PLACEHOLDER — Add real customer reviews through the admin panel. Do not publish placeholder testimonials publicly.]',
      serviceName: 'Tankless Water Heater Installation',
      date: '2025-01-18',
      verified: true,
      source: 'google',
    },
  ],

  defaultBlogPosts: [
    {
      id: 'post-1',
      title: 'How to Prevent Frozen Pipes During a Colorado Cold Snap',
      slug: 'prevent-frozen-pipes-colorado-winter',
      excerpt: 'Essential steps every Denver homeowner should take when sub-zero temperatures arrive in the Front Range.',
      content: 'Detailed guide on insulation, thermostat settings, and drip techniques...',
      category: 'Plumbing Tips',
      imageUrl: '/assets/service-detail-2.jpg',
      publishedAt: 'February 12, 2025',
      author: 'PipeFlow Team',
      featured: true,
      published: true,
    },
    {
      id: 'post-2',
      title: 'Heat Pumps vs. Traditional Furnaces: What Makes Sense in Colorado?',
      slug: 'heat-pumps-vs-furnaces-colorado-climate',
      excerpt: 'Compare dual-fuel hybrid heat pumps with standard gas furnaces for altitude efficiency and energy savings.',
      content: 'Breakdown of SEER2 ratings, heating COP at high elevation, and utility rebates...',
      category: 'HVAC Guide',
      imageUrl: '/assets/hero-hvac-tech.jpg',
      publishedAt: 'January 28, 2025',
      author: 'PipeFlow Team',
      featured: true,
      published: true,
    },
    {
      id: 'post-3',
      title: '5 Warning Signs Your Water Heater Is About to Fail',
      slug: 'warning-signs-water-heater-failure',
      excerpt: 'Rusty hot water, strange rumbling sounds, or slow recovery times? Here is what to inspect before a leak.',
      content: 'Guide to sediment buildup, anode rod lifespan, and pressure relief valves...',
      category: 'Plumbing Guide',
      imageUrl: '/assets/service-plumbing.jpg',
      publishedAt: 'January 14, 2025',
      author: 'PipeFlow Team',
      featured: false,
      published: true,
    },
  ],

  defaultFAQs: [
    {
      id: '1',
      question: 'What areas does PipeFlow Co. serve?',
      answer:
        'We serve Denver and the surrounding Colorado communities including Aurora, Lakewood, Englewood, Littleton, Arvada, Westminster, Thornton, Centennial, Parker, Brighton, and Castle Rock. Additional service areas can be configured through our admin panel.',
      order: 1,
    },
    {
      id: '2',
      question: 'Do you offer emergency plumbing or HVAC service?',
      answer: 'Yes! We provide rapid emergency response for severe leaks, burst pipes, no-heat calls in winter, and air conditioning breakdowns.',
      order: 2,
    },
    {
      id: '3',
      question: 'How do I schedule a service appointment?',
      answer:
        'You can book online directly using our booking form, submit a request on our homepage, or call our dispatch desk at (720) 555-0100.',
      order: 3,
    },
    {
      id: '4',
      question: 'Are your technicians licensed and insured in Colorado?',
      answer: 'Yes, all PipeFlow technicians are licensed, insured, and thoroughly background-checked trades professionals.',
      order: 4,
    },
    {
      id: '5',
      question: 'Do you provide upfront pricing before starting work?',
      answer: 'Always. We diagnose the situation, explain your options in plain language, and give you an upfront quote before any work begins.',
      order: 5,
    },
  ],

  defaultTrustBadges: [
    { id: '1', label: 'Licensed & Insured', iconName: 'shield-check', description: 'Fully bonded Colorado professionals' },
    { id: '2', label: 'Same-Day Service', iconName: 'clock', description: 'Fast response when you need it most' },
    { id: '3', label: '24/7 Emergency', iconName: 'alert-circle', description: 'Around-the-clock emergency response' },
    { id: '4', label: 'Upfront Pricing', iconName: 'dollar-sign', description: 'Transparent quotes with no surprises' },
    { id: '5', label: 'Local Colorado Team', iconName: 'map-pin', description: 'Proudly serving the Denver metro area' },
    { id: '6', label: 'Plumbing + HVAC', iconName: 'wrench', description: 'Complete residential mechanical care' },
  ],

  social: {
    facebook: 'https://facebook.com/pipeflowco', // [PLACEHOLDER]
    instagram: 'https://instagram.com/pipeflowco', // [PLACEHOLDER]
    google: 'https://g.page/pipeflowco', // [PLACEHOLDER]
  },

  seo: {
    defaultTitle: 'PipeFlow Co. — Denver Plumbing & HVAC Services',
    titleTemplate: '%s | PipeFlow Co.',
    defaultDescription:
      'Reliable Plumbing & HVAC Service When You Need It. PipeFlow Co. provides expert plumbing and HVAC solutions across Denver and surrounding Colorado communities. Same-day service available. Upfront pricing.',
    keywords: [
      'plumbing Denver',
      'HVAC Denver',
      'Denver plumber',
      'Denver heating and cooling',
      'emergency plumber Denver',
      'Colorado plumbing and HVAC',
      'drain cleaning Denver',
      'water heater Denver',
      'furnace repair Denver',
      'AC repair Denver',
      'heat pumps Denver',
    ],
  },
}
